-- Seed dữ liệu mẫu cho hệ thống quản lý du lịch
-- Chạy: node backend/src/sql/seed.js
-- Mật khẩu admin: Admin@2025 | staff: Staff@2025 | user: User@2025

-- NOTE: Passwords below are bcrypt hashes generated by seed.js
-- Do NOT edit manually. Run `npm run seed` from backend/ directory.

INSERT INTO tours (title, destination, itinerary, price, start_date, end_date, slots, image_url) VALUES
('Tour Đà Nẵng 3N2D', 'Đà Nẵng', 'Ngày 1: TP.HCM - Đà Nẵng\nNgày 2: Bà Nà Hills - Cầu Vàng\nNgày 3: Phố Cổ Hội An - TP.HCM', 3500000, '2026-06-10', '2026-06-12', 30, 'https://images.unsplash.com/photo-1559592413-7cec4d0cae2b?auto=format&fit=crop&w=800&q=80'),
('Tour Phú Quốc 4N3D', 'Phú Quốc', 'Ngày 1: TP.HCM - Phú Quốc\nNgày 2: Safari & Cáp treo\nNgày 3: Hòn Thơm - Snorkeling\nNgày 4: Phú Quốc - TP.HCM', 5500000, '2026-07-02', '2026-07-05', 25, 'https://images.unsplash.com/photo-1573715806542-7a0ed6f4a4e6?auto=format&fit=crop&w=800&q=80'),
('Tour Hà Nội - Hạ Long 5N4D', 'Hạ Long', 'Ngày 1: Bay ra Hà Nội\nNgày 2-4: Vịnh Hạ Long\nNgày 5: Về TP.HCM', 7200000, '2026-08-15', '2026-08-19', 20, 'https://images.unsplash.com/photo-1573390927200-e7d58d8ee57c?auto=format&fit=crop&w=800&q=80');

INSERT INTO articles (tour_id, title, content, image_url) VALUES
(1, 'Kinh nghiệm đi Đà Nẵng', 'Đà Nẵng là thành phố biển tuyệt đẹp với nhiều điểm tham quan nổi tiếng như Bà Nà Hills, Cầu Vàng và Phố Cổ Hội An gần đó. Thời tiết Đà Nẵng đẹp nhất vào mùa hè từ tháng 5 đến tháng 8.', 'https://images.unsplash.com/photo-1559592413-7cec4d0cae2b?auto=format&fit=crop&w=1200&q=80'),
(2, 'Khám phá Phú Quốc', 'Phú Quốc - hòn đảo ngọc của Việt Nam với bãi biển trong xanh và hải sản tươi ngon. Đừng bỏ qua chuyến cáp treo vượt biển dài nhất thế giới!', 'https://images.unsplash.com/photo-1573715806542-7a0ed6f4a4e6?auto=format&fit=crop&w=1200&q=80'),
(NULL, 'Cẩm nang du lịch Việt Nam 2026', 'Hướng dẫn toàn diện cho du khách khi khám phá Việt Nam. Từ ẩm thực đường phố đến các điểm check-in nổi tiếng, bài viết này sẽ giúp bạn lên kế hoạch chuyến đi hoàn hảo.', 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&w=1200&q=80');

INSERT INTO activity_logs (user_id, role, action, details) VALUES
(NULL, 'system', 'System initialized', 'Database schema created'),
(NULL, 'system', 'Sample data inserted', 'Tours and articles seeded');
